import { create } from 'zustand'
import { Howl } from 'howler'

// Lazily instantiated Howl instances — created on first play, not on import.
// This avoids browser autoplay policy issues before any user interaction.
const howls = {}

function getHowl(key) {
  if (howls[key]) return howls[key]

  const sources = {
    click:        ['/sounds/click.mp3', '/sounds/click.wav'],
    open:         ['/sounds/click.mp3'],
    close:        ['/sounds/close.wav'],
    minimize:     ['/sounds/minimize.wav'],
    notification: ['/sounds/notification.wav'],
    /* Power-on chime. AAC rather than WAV: it is the one long clip here, and
       2.4s of 16-bit PCM is 207 KB against 15 KB encoded. Generated by
       assets/sounds/generate.cjs — an original G-major spread, deliberately
       not Apple's startup sound, which is a registered trademark. */
    chime:        ['/sounds/chime.m4a'],
    // Trash: a file landing in the basket, and the basket being emptied.
    // Mapped onto the existing clips for now — swap in the real rustle and
    // crumple here and nothing else has to change.
    trash:        ['/sounds/minimize.wav'],
    emptyTrash:   ['/sounds/close.wav'],
  }

  if (!sources[key]) return null

  howls[key] = new Howl({
    src: sources[key],
    volume: key === 'chime' ? 0.45 : 0.6,
    preload: true,
  })

  return howls[key]
}

const useSoundStore = create((set, get) => ({
  isEnabled: true,

  toggleSound: () => {
    const next = !get().isEnabled
    // Mute / unmute all loaded Howl instances globally
    Howler.mute(!next)
    set({ isEnabled: next })
  },

  play: (soundKey) => {
    if (!get().isEnabled) return
    try {
      const howl = getHowl(soundKey)
      if (howl) howl.play()
    } catch {
      // silently fail
    }
  },
}))

export default useSoundStore
